Repository CropAi/Frontend, pull requests merged in 2020-05, with the labels that each got.

#300 updating color_palette
  src/contributors/user_palette.js
Labels: easy, gssoc20

#297 Disease added
  index.html
Labels: beginner, gssoc20

#296 add gssoc2020 label
  .github/workflows/pullRequestLabeller.yml
Labels: beginner, gssoc20

#311 Added the guidelines to use the application
  docs/README.md
Labels: easy, gssoc20

#308 Modification in greetings and labeller
  .github/labeller.yml
  .github/workflows/greetings.yml
  .github/workflows/pullRequestLabeller.yml
  index.html
Labels: easy, gssoc20

#307 Update user_palette.js #303
  src/contributors/user_palette.js
Labels: easy, gssoc20

#305 html validator errors fixed in index.html
  index.html
Labels: easy, gssoc20

#316 Update user_palette.js
  src/contributors/user_palette.js
Labels: easy, gssoc20

#317 Update user_palette.js
  src/contributors/user_palette.js
Labels: easy, gssoc20

#304 added a back button to return to the previous state
  index.html
  src/assets/index.css
Labels: PR: reviewed-changes-requested, medium
