Repository CropAi/Frontend, pull requests merged in 2020-04, with the labels that each got.

#9 Added one sample of landing page
  Web Designs/design-1/landing-page/Landing Page.png
  Web Designs/design-1/landing-page/resources.txt
Labels: easy, gssoc20

#11 Added design for results page
  Web Designs/design-1/result-page/Resources.txt
  Web Designs/design-1/result-page/Result Page.png
Labels: beginner, gssoc20

#17 Input Page Design
  Web Designs/design-2/Input Page/Input Page.xd
  Web Designs/design-2/Input Page/Screenshot.png
Labels: gssoc20, medium

#15 Result page Design
  Web Designs/design-2/Result Page/Result page.xd
  Web Designs/design-2/Result Page/screnshot.png
Labels: gssoc20, medium

#29 hidden_class_added
  src/assets/index.css
Labels: easy, gssoc20

#49 Corrected md syntax on important links
  README.md
Labels: beginner, gssoc20

#50 added_button
  src/assets/index.css
  src/index.html
Labels: gssoc20, medium

#60 added contribute.md
  CONTRIBUTE.md
Labels: easy, gssoc20

#62 Update Documentation
  CODE_OF_CONDUCT.md
  CONTRIBUTE.md
  README.md
Labels: beginner, gssoc20

#56 Create PR_template.md
  PR_template.md
Labels: easy, gssoc20

#43 Add logo design no.5
  logo-designs/logodesign-3.png
  logodesign-3.png
Labels: gssoc20, medium

#67 Adding Social Media to the documentation
  docs/README.md
Labels: beginner, gssoc20

#72 href and tree changed
  designs/Web Designs/design-3/Resources/tree.png
  src/landing pages/landing-page-3/landing3.html
Labels: easy, gssoc20

#76 New logo added
  designs/logo-designs/submitted-logos/logodesign-7.png
Labels: gssoc20, medium

#77 Input Form created
  src/assets/index.css
  src/index.html
Labels: gssoc20, medium

#78 Added Contribution-page
  designs/contributors/contributors-5/background1.jpg
  designs/contributors/contributors-5/background2.jpg
  designs/contributors/contributors-5/contribution Page on smaller device.png
  designs/contributors/contributors-5/contribution Page.png
  designs/contributors/contributors-5/person1.jpeg
  designs/contributors/contributors-5/person2.jpg
Labels: gssoc20, medium

#84 Added url to logo
  src/index.html
Labels: beginner, gssoc20

#94 Result_container_button
  src/assets/index.css
  src/index.html
Labels: beginner, gssoc20

#104 delete lib folder
  src/lib/temp.css
Labels: beginner, gssoc20

#107 modified_img_src
  src/assets/index.js
Labels: gssoc20, medium

#108 Remodeling of Landing page-2
  src/assets/landing-2.css
  src/landing pages/landing-page-2/landing2.html
Labels: gssoc20, medium

#97 Landing Page-3 Rectified
  src/assets/landing-3.css
  src/landing pages/landing-page-3/landing3.html
Labels: gssoc20, hard

#123 Added dummy svg image in input page
  src/assets/index.css
  src/assets/index.js
  src/img/dummy-image.svg
  src/index.html
Labels: beginner, gssoc20

#124 Update navbar links in Landing Page 2
  src/assets/landing-2.css
  src/landing pages/landing-page-2/landing2.html
Labels: beginner, gssoc20

#125 Update navbar contibutor.html
  src/assets/contributor.css
  src/contributors page/contributor.html
Labels: beginner, gssoc20

#128 update readme
  designs/logo-designs/gssoc-logo-with-text.png
  docs/README.md
Labels: beginner, gssoc20

#126 Add logo in title bar (favicon) as per #121
  src/contributors page/contributor.html
  src/index.html
  src/landing pages/landing-page-2/landing2.html
  src/landing pages/landing-page-3/landing3.html
Labels: beginner, gssoc20

#112 Js Script for fetching user data
  src/contributors page/script_for_fetching_userdata.js
Labels: gssoc20, hard

#140 :bug: fix upload file button
  src/assets/index.css
  src/index.html
Labels: easy, gssoc20

#156 correct closing button tag of Analyze
  src/index.html
Labels: beginner, gssoc20

#158 :up: file type check regex JS
  src/assets/index.js
Labels: gssoc20, medium

#159 Create default_contributors.js
  src/contributors page/default_contributors.js
Labels: easy, gssoc20

#160 CSS of button and font-weight of heading changed
  src/assets/index.css
Labels: beginner, gssoc20

#161 Result Image added for smaller Screens
  src/assets/index.css
Labels: easy, gssoc20

#162 Overlap issue
  src/assets/index.css
Labels: beginner, gssoc20

#172 Adding divs to contributor.html
  src/contributors page/contributor.html
Labels: beginner, gssoc20

#176 AJAX call integration
  src/assets/index.js
  src/index.html
Labels: gssoc20, hard

#178 animation on about button added
  src/assets/index.css
  src/assets/index.js
  src/index.html
Labels: easy, gssoc20

#179 Addition of color palette
  src/contributors page/user_palette.js
Labels: easy, gssoc20

#184 Contributor button
  src/assets/contributor.css
  src/contributor.js
  src/contributors page/contributor.html
Labels: gssoc20, medium

#185 Update user_palette.js
  src/contributors page/user_palette.js
Labels: easy, gssoc20

#196 Remove unnecessary comments [index.js]
  src/assets/index.js
Labels: beginner, gssoc20

#217 loading-spinner
  src/assets/index.js
  src/index.html
Labels: gssoc20, medium

#216 added color
  src/contributors page/user_palette.js
Labels: easy, gssoc20

#221 u_palette.js
  src/contributors page/user_palette.js
Labels: easy, gssoc20

#220 Disabled the hover underline on icon
  src/assets/contributor.css
Labels: beginner, gssoc20

#222 default_contributors.js updated
  src/contributors page/default_contributors.js
Labels: easy, gssoc20

#224 call create_user_card for each contributor
  src/assets/contributor.js
Labels: beginner, gssoc20

#228 Moving index.html out of src
  index.html
  src/contributors page/contributor.html
  src/landing pages/landing-page-2/landing2.html
  src/landing pages/landing-page-3/landing3.html
Labels: gssoc20, medium

#243 open products in new tab
  src/assets/index.js
Labels: beginner, gssoc20

#241 Title added to contributor.html
  src/contributors page/contributor.html
Labels: beginner, gssoc20

#240 Update heading of index.html
  index.html
Labels: beginner, gssoc20

#244 Hover effect
  src/assets/contributor.css
Labels: beginner, gssoc20

#247 random color to card body
  src/assets/contributor.js
Labels: gssoc20, medium

#248 Adding border-radius to the bottom of the card
  src/assets/contributor.css
Labels: easy, gssoc20

#250 update titles
  index.html
  src/assets/index.js
Labels: easy, gssoc20

#259 Added countdown while loading
  index.html
  src/assets/index.js
Labels: gssoc20, medium

#256 Landing page imp
  src/assets/landing-3.css
  src/landingPages/landingPage2/index.html
  src/landingPages/landingPage3/index.html
Labels: gssoc20, medium

#267 submit btn fix
  index.html
  src/assets/index.css
Labels: easy, gssoc20

#266 name label
  index.html
  src/assets/index.js
Labels: beginner, gssoc20

#264 added new color palette #170
  src/contributors/user_palette.js
Labels: easy, gssoc20

#263 Working on SEO:research part-trialLink
  index.html
Labels: gssoc20, medium

#269 added new object to color palette
  src/contributors/user_palette.js
Labels: easy, gssoc20

#272 Update index.css
  src/assets/index.css
Labels: beginner, gssoc20

#271 License file added
  docs/LICENSE.md
Labels: beginner, gssoc20

#274 Best practice audit improvement
  index.html
  src/assets/index.js
Labels: gssoc20, medium

#280 comments added in index.js
  src/assets/index.js
Labels: beginner, gssoc20

#278 Bug fix:Cards
  src/assets/contributor.css
Labels: easy, gssoc20

#287 Contributing.md file
  docs/CONTRIBUTING.md
Labels: easy, gssoc20

#288 Contributing.md file (2)
  docs/CONTRIBUTING.md
Labels: duplicate

#282 added the grreting action.
  .github/workflows/greetings.yml
Labels: beginner, gssoc20

#279 image label with tooltip
  index.html
  src/assets/index.css
  src/assets/index.js
Labels: gssoc20, medium

#291 275 - Update Readme (Added a license)
  docs/README.md
Labels: beginner, gssoc20

#290 gssoc labeller action.
  .github/labeller.yml
Labels: beginner, gssoc20

#284 added mergeConflicts labeller.
  .github/merge-conflicts.yml
Labels: beginner, gssoc20

#293 Responsiveness and content ratio LP-2
  src/assets/landing-2.css
  src/landingPages/landingPage2/index.html
Labels: gssoc20, medium

#289 Button alignments
  index.html
  src/assets/index.css
Labels: gssoc20, medium
